version: '3.8'
services:
  back-books:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back-books
    restart: unless-stopped
    ports:
      - "80:5000"
    volumes:
      - .:/app
    depends_on:
      - db-books

  db-books:
    image: mysql:5.7.22
    container_name: db-books
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: books
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
